### PR TITLE
feat: save contact to addressbook

### LINKED ISSUE #3530: Add contact
### Is the feature you are looking for already implemented in the library?

- [x] I have reviewed the implemented features.

### Is your "solution" already implemented in an opened pull request?

- [x] I have reviewed the existing pull requests.

### Is your feature request related to a problem? Please describe.

 I see this feature is already available on the web, can it be added now? #195

### Describe the solution you'd like.

 I see this feature is already available on the web, can it be added now? #195

### Describe an alternate solution if you have one.

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by alechkos**
<p align="center">
    <a href="https://github.com/sponsors/alechkos/">
        
    </a>
</p>

# PR Details

## Description

**The PR adds a new functionality for saving/editing/deleting contacts in addressbook:**
- [**`Client.saveOrEditAddressbookContact`**<a href="https://github.com/pedroslopez/whatsapp-web.js/pull/3533#usage-example-b1" id="usage-example-b1"/>](https://github.com/pedroslopez/whatsapp-web.js/pull/3533#usage-example1) for saving new contact to user's addressbook or editing the existing one.
- [**`Client.deleteAddressbookContact`**<a href="https://github.com/pedroslopez/whatsapp-web.js/pull/3533#usage-example-b2" id="usage-example-b2"/>](https://github.com/pedroslopez/whatsapp-web.js/pull/3533#usage-example2) for deleting the contact from user's addressbook.

## Related Issue

closes #3530

---

### 1. [To save a new contact in user's addressbook:](https://github.com/pedroslopez/whatsapp-web.js/pull/3533#usage-example-b1) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/3533#usage-example1" id="usage-example1"/>
```js

// client initialization...

client.on('ready', async () => {
    /* If set to true, the contact will also be saved to the user's address book on their phone. False by default */
    const syncToAddressbook = true;

    /* Saving a new contact: */
    await client.saveOrEditAddressbookContact(
        "17132222222",
        "John",
        "Doe",
        syncToAddressbook
    );

    /* Editing an existing contact: */
    await client.saveOrEditAddressbookContact(
        "17132222222",
        "Paul",
        "Smenis",
        syncToAddressbook
    );
});
```

### 2. [To delete an existing contact from addressbook:](https://github.com/pedroslopez/whatsapp-web.js/pull/3533#usage-example-b2) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/3533#usage-example2" id="usage-example2"/>
```js
// client initialization...

client.on('ready', async () => {
    await client.deleteAddressbookContact("17132222222");
});
```

---

## To try this PR by yourself you can run one of the following commands:

- **NPM**
```powershell
npm install github:alechkos/whatsapp-web.js#save-contact
```
- **YARN**
```powershell
yarn add github:alechkos/whatsapp-web.js#save-contact
```

---

## How Has The PR Been Tested

Tested with a code provided in [usage example](https://github.com/pedroslopez/whatsapp-web.js/pull/3533#usage-example).

---

## [Types of Changes](https://github.com/pedroslopez/whatsapp-web.js/pull/3533#types-of-changes-b) <a href="https://github.com/pedroslopez/whatsapp-web.js/pull/3533#types-of-changes" id="types-of-changes"/>
- [ ] Dependency change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix/feature that would cause existing functionality to change)

## Checklist
- [X] My code follows the code style of this project
- [ ] I have updated the usage example accordingly (example.js)
- [X] I have updated the documentation accordingly (index.d.ts)

### CODE REVIEW

**Comment by wonddok** [comment]
thanks

**Review by shirser121 — APPROVED** [review]
LGTM

**Review by tuyuribr — APPROVED** [review]
Good work

**Comment by l0pu** [comment]
it doesnt work in Chrome 109.0.5414.168 :

Error: Evaluation failed: TypeError: e.trim is not a function
    at Object.<anonymous> (https://static.whatsapp.net/rsrc.php/v4iwCL4/ym/l/rt/IfzrW78cvt-.js:372:2144)
    at Generator.next (<anonymous>)
    at h (https://static.whatsapp.net/rsrc.php/v4/yU/r/qgLOtQHluXZ.js:149:125)
    at g (https://static.whatsapp.net/rsrc.php/v4/yU/r/qgLOtQHluXZ.js:149:349)
    at ExecutionContext._ExecutionContext_evaluate (c:\Program Files\nodejs\wwebjs-bot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.
js:229:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ExecutionContext.evaluate (c:\Program Files\nodejs\wwebjs-bot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:107:16)
    at async Client.saveOrEditAddressbookContact (c:\Program Files\nodejs\wwebjs-bot\node_modules\whatsapp-web.js\src\Client.js:2161:16)
