### ISSUE TITLE
Execution context was destroyed after 2–10 hours (v1.34.4) + getLastMsgKeyForAction is not a function (v1.34.6)

### ISSUE THREAD

**Issue by ahmedramzyon** [pedroslopez/whatsapp-web.js#127056]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Is this a problem caused by your code, or is it specifically because of the library?

- [x] I have double-checked my code carefully.

### Describe the bug.

I am experiencing two related issues while running a WhatsApp automation bot using whatsapp-web.js.

1️⃣ On version 1.34.4

The bot runs normally, but after approximately 2–10 hours, it crashes with:

Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (...)
    at async Client.inject (...)

2️⃣ After upgrading to 1.34.6

The previous crash disappears, but a new error appears immediately when sending messages:

TypeError: e.getLastMsgKeyForAction is not a function
    at window.WWebJS.sendSeen
    at Client.sendMessage

This occurs during sendMessage and appears related to sendSeen.

### Expected Behavior

🔁 Steps to Reproduce
Issue 1 (v1.34.4)

Start the bot

Let it run normally

After 2–10 hours

Bot crashes with:

Execution context was destroyed, most likely because of a navigation.

Issue 2 (v1.34.6)

Upgrade to v1.34.6

Send a message using client.sendMessage() or message.reply()

Immediately crashes with:

e.getLastMsgKeyForAction is not a function

Stack trace points to:

window.WWebJS.sendSeen

### Steps to Reproduce the Bug or Issue

🎯 Expected Behavior

The bot should remain stable for long-running sessions.

sendMessage should not throw internal WhatsApp function errors.

Internal WhatsApp Web changes should not break sendSeen.

🧠 Observations / Hypothesis

The long-session crash may be related to WhatsApp Web reloading internally.

The getLastMsgKeyForAction error seems caused by a recent WhatsApp Web internal change.

The issue appears inside sendSeen before message sending.

Possibly related to recent WhatsApp Web version update.

📋 Minimal Example

Basic sendMessage:

await client.sendMessage(chatId, "Test message");

or

await message.reply("Test reply");

Both can trigger the error in 1.34.6.

### WhatsApp Account Type

WhatsApp Business

### Browser Type

Google Chrome

### Operation System Type

Windows

### Phone OS Type

Android

### WhatsApp-Web.js Version

1.34.4 (long session crash)  1.34.6 (sendSeen error)

### WhatsApp Web Version

Latest (bundled with Chromium)

### Node.js Version

v18.20.8

### Authentication Strategy

LocalAuth

**Comment by silveira2974** [comment]
It's happening the same with me.

**Comment by BenyFilho** [comment]
I tested, and everything is working fine.

<img width="746" height="244" alt="Image" src="https://github.com/user-attachments/assets/d5f551dd-3f43-4d30-a663-c4aae8dfe639" />

**Comment by silveira2974** [comment]
Yes @BenyFilho, it is, but only for the first 10-24 hours. After that, it simply stops working, loses communication with the WhatsApp server, and stops responding to client.sendMessage requests.

**Comment by BenyFilho** [comment]
> Yes [@BenyFilho](https://github.com/BenyFilho), it is, but only for the first 10-24 hours. After that, it simply stops working, loses communication with the WhatsApp server, and stops responding to client.sendMessage requests.

So, you’ll need to debug this and provide more information.

[Before Asking On Discord Or Opening An Issue.pdf](https://github.com/user-attachments/files/25319009/Before.Asking.On.Discord.Or.Opening.An.Issue.pdf)

**Comment by ahmedramzyon** [comment]
> > Yes [@BenyFilho](https://github.com/BenyFilho), it is, but only for the first 10-24 hours. After that, it simply stops working, loses communication with the WhatsApp server, and stops responding to client.sendMessage requests.
> 
> So, you’ll need to debug this and provide more information.
> 
> [Before Asking On Discord Or Opening An Issue.pdf](https://github.com/user-attachments/files/25319009/Before.Asking.On.Discord.Or.Opening.An.Issue.pdf)
 


Alright brother, I’ll send you all the details I can so we can solve this issue, God willing.

Right now, I’m using version 1.34.4 of the library, and it works very well on this version. However, after some time, this error starts appearing.


C:\Users\Administrator\Desktop\whatsapp 2.0.1\coooood\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:457
        throw new Error('Execution context was destroyed, most likely because of a navigation.');
              ^

Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (C:\Users\Administrator\Desktop\whatsapp 2.0.1\coooood\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:457:15)
    at async #evaluate (C:\Users\Administrator\Desktop\whatsapp 2.0.1\coooood\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:340:64)
    at async ExecutionContext.evaluate (C:\Users\Administrator\Desktop\whatsapp 2.0.1\coooood\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:277:16)
    at async IsolatedWorld.evaluate (C:\Users\Administrator\Desktop\whatsapp 2.0.1\coooood\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\IsolatedWorld.js:100:16)
    at async CdpFrame.evaluate (C:\Users\Administrator\Desktop\whatsapp 2.0.1\coooood\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Frame.js:362:20)
    at async CdpPage.evaluate (C:\Users\Administrator\Desktop\whatsapp 2.0.1\coooood\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:826:20)
    at async Client.inject (C:\Users\Administrator\Desktop\whatsapp 2.0.1\coooood\node_modules\whatsapp-web.js\src\Client.js:106:19)
    at async C:\Users\Administrator\Desktop\whatsapp 2.0.1\coooood\node_modules\whatsapp-web.js\src\Client.js:383:13

Node.js v18.20.8
Press any key to continue . . .

**Comment by ahmedramzyon** [comment]
<img width="1114" height="767" alt="Image" src="https://github.com/user-attachments/assets/979e9793-4a91-4e36-9ecd-2790f92f6a1c" />

Right now, the only change I made was upgrading the library from version 1.34.4 to 1.34.6.

After that, I tested the bot normally — it logged in successfully and everything seemed fine. However, at the moment it tries to send a message to a specific group or directly to a user, this error occurs. I don’t know the reason.

Please let me know if you need any specific details or a particular part of the code, and I’ll send it to you immediately.

Thank you for your great effort and for this excellent library.




❌ Error while processing orders [683215]: e.getLastMsgKeyForAction is not a function
I (https://static.whatsapp.net/rsrc.php/v4iAM04/yc/l/en_US-j/3JJWKHeu5-P.js:1587:5016)
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [TypeError]: e.getLastMsgKeyForAction is not a function
I (https://static.whatsapp.net/rsrc.php/v4iAM04/yc/l/en_US-j/3JJWKHeu5-P.js:1587:5016)
Object.<anonymous> (https://static.whatsapp.net/rsrc.php/v4iAM04/yc/l/en_US-j/3JJWKHeu5-P.js:1587:1662)
    at window.WWebJS.sendSeen (evaluate at Binding.<anonymous> (C:\Users\h\OneDrive\Desktop\whatsapp 2.0.1(2) - Copy\whatsapp 2.0.1\whatsapp 2.0.1\coooood\node_modules\whatsapp-web.js\src\Client.js:265:36), <anonymous>:13:40)
    at #evaluate (C:\Users\h\OneDrive\Desktop\whatsapp 2.0.1(2) - Copy\whatsapp 2.0.1\whatsapp 2.0.1\coooood\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:391:56)
    at async ExecutionContext.evaluate (C:\Users\h\OneDrive\Desktop\whatsapp 2.0.1(2) - Copy\whatsapp 2.0.1\whatsapp 2.0.1\coooood\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:277:16)
    at async IsolatedWorld.evaluate (C:\Users\h\OneDrive\Desktop\whatsapp 2.0.1(2) - Copy\whatsapp 2.0.1\whatsapp 2.0.1\coooood\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\IsolatedWorld.js:100:16)
    at async CdpFrame.evaluate (C:\Users\h\OneDrive\Desktop\whatsapp 2.0.1(2) - Copy\whatsapp 2.0.1\whatsapp 2.0.1\coooood\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Frame.js:362:20)
    at async CdpPage.evaluate (C:\Users\h\OneDrive\Desktop\whatsapp 2.0.1(2) - Copy\whatsapp 2.0.1\whatsapp 2.0.1\coooood\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:826:20)
    at async Client.sendMessage (C:\Users\h\OneDrive\Desktop\whatsapp 2.0.1(2) - Copy\whatsapp 2.0.1\whatsapp 2.0.1\coooood\node_modules\whatsapp-web.js\src\Client.js:1083:25)
    at async Client.<anonymous> (C:\Users\h\OneDrive\Desktop\whatsapp 2.0.1(2) - Copy\whatsapp 2.0.1\whatsapp 2.0.1\coooood\index\index.js:176:5)
    at v (https://static.whatsapp.net/rsrc.php/v4iAM04/yc/l/en_US-j/3JJWKHeu5-P.js:1586:1284)
    at <anonymous> (https://static.whatsapp.net/rsrc.php/v4/yP/r/UnXae5I7-4r.js:106:276)
    at <anonymous> (https://static.whatsapp.net/rsrc.php/v4/yP/r/UnXae5I7-4r.js:106:407)
    at i (https://static.whatsapp.net/rsrc.php/v4/yP/r/UnXae5I7-4r.js:106:348)
    at l (https://static.whatsapp.net/rsrc.php/v4/yP/r/UnXae5I7-4r.js:106:124)
    at <anonymous> (https://static.whatsapp.net/rsrc.php/v4iAM04/yc/l/en_US-j/3JJWKHeu5-P.js:1586:1661)
    at I (https://static.whatsapp.net/rsrc.php/v4iAM04/yc/l/en_US-j/3JJWKHeu5-P.js:1586:5015)

Node.js v18.20.8
Press any key to continue . . .

**Comment by ahmedramzyon** [comment]
<img width="953" height="399" alt="Image" src="https://github.com/user-attachments/assets/2605ea54-bedb-4afe-b761-b535aabd2cd3" />

I think this code might be helpful in understanding the problem.

**Comment by ahmedramzyon** [comment]
webVersionCache: {
  type: 'remote',
  remotePath:
    'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.3000.1031490220-alpha.html'
},

Brother, I removed that code and tested it again — it’s working perfectly now without any issues. Thank you.

Now I’ll continue testing the bot to see if the original issue still happens after some time, like before, or if it remains stable.

**Comment by BenyFilho** [comment]
> webVersionCache: { type: 'remote', remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.3000.1031490220-alpha.html' },
> 
> Brother, I removed that code and tested it again — it’s working perfectly now without any issues. Thank you.
> 
> Now I’ll continue testing the bot to see if the original issue still happens after some time, like before, or if it remains stable.

That I was talking about, how cold I know you are using an old version of WebCache? You guys are posting here only an error without any context, and expecting us to guess what happens.
I'm happy that you solved your problem.
