### ISSUE TITLE
requestPairingCode error: Evaluation failed: TypeError: window.onCodeReceivedEvent is not a function

### ISSUE THREAD

**Issue by just-shadyumbrella** [pedroslopez/whatsapp-web.js#3709]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Is this a problem caused by your code, or is it specifically because of the library?

- [x] I have double-checked my code carefully.

### Describe the bug.

Fresh install, not logged in obviously.

```sh
INFO  [2025-08-17T14:17:33.783Z] [index:client]                   Client version:  2.3000.1025996334
224 |         }
225 |         throw error;
226 |     }
227 |     const { exceptionDetails, result: remoteObject } = await callFunctionOnPromise.catch(rewriteError);
228 |     if (exceptionDetails) {
229 |         throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
                    ^
error: Evaluation failed: TypeError: window.onCodeReceivedEvent is not a function
    at pptr://__puppeteer_evaluation_script__:18:23
      at _ExecutionContext_evaluate (V:\User\Documents\Project\Private\wbt\node_modules\.pnpm\puppeteer-core@18.2.1_encoding@0.1.13\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:229:15)

Bun v1.2.20 (Windows x64)
```

### Expected Behavior

Previously worked with version `1.31.1-alpha.0`

### Steps to Reproduce the Bug or Issue

My first attempt is to update my libs (`pnpm up`), but then got this error, so I attempt quick double check lib reversing: 
```sh
pnpm add whatsapp-web.js@latest
bun run .
```

My `requestPairingCode` code clip:
```ts
client.on('qr', async (qr) => {
  console.log('Scan QR:')
  qrcode.generate(qr, { small: true }) // QR print successfully however
  if (PHONE_NUMBER) {
    console.log('Pairing Code:', await client.requestPairingCode(PHONE_NUMBER)) // Error, yep...
  }
})
```

Alpha version:
```sh
pnpm add whatsapp-web.js@next
bun run .
```

Same code, both QR and pairing code printed, no error.

### WhatsApp Account Type

Standard

### Browser Type

Google Chrome

### Operation System Type

Windows

### Phone OS Type

Any

### WhatsApp-Web.js Version

1.32.0

### WhatsApp Web Version

2.3000.1025996334

### Node.js Version

node: "24.3.0", bun: "1.2.20"

### Authentication Strategy

LocalAuth

**Comment by alechkos** [comment]
`Client.requestPairingCode` is a private function that supposed to work when you pass `pairWithPhoneNumber` object to `Client` constractor:
```js
const client = new Client({
  // ...,
  pairWithPhoneNumber: {
    phoneNumber: number,
  },
  // ...,
});
```

Then you should listen to the incoming code:
```js
client.on('code', (code) => {
    console.log('Pairing code:', code);
});
```

**Comment by just-shadyumbrella** [comment]
Ohh, that's now a new method, could i do QR and code pairing alongside?

**Comment by codarbind** [comment]
> `Client.requestPairingCode` is a private function that supposed to work when you pass `pairWithPhoneNumber` object to `Client` constractor:
> 
> const client = new Client({
>   // ...,
>   pairWithPhoneNumber: {
>     phoneNumber: number,
>   },
>   // ...,
> });
> Then you should listen to the incoming code:
> 
> client.on('code', (code) => {
>     console.log('Pairing code:', code);
> });

many thanks, but I am facing this issue still

<img width="2427" height="1037" alt="Image" src="https://github.com/user-attachments/assets/25cccda9-0aef-4c8e-be8b-450fe3b9f9bb" />

here is screenshot of the set up and error

**Comment by Chri6s** [comment]
Same issue. Anyhow I try (calling the function directly or passing it thru the constructor) I still run into the error seen above:
```
/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229
throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
          ^
Error: Evaluation failed: b
```
Another issue opened just last week also mentions directly this problem: #3763

**Comment by corzel** [comment]
> Same issue. Anyhow I try (calling the function directly or passing it thru the constructor) I still run into the error seen above:
> 
> ```
> /usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229
> throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
>           ^
> Error: Evaluation failed: b
> ```
> 
> Another issue opened just last week also mentions directly this problem: [#3763](https://github.com/pedroslopez/whatsapp-web.js/issues/3763)

I also started getting this same error: "Error: Evaluation failed: b" The problem was with the phone number validation. I had +55098765432, but it should be +55098765432@c.us.

In case this information is helpful to anyone.

**Comment by seanesbo** [comment]
for 
Error: Evaluation failed: b
use #3706
