### ISSUE TITLE
window.Store.MediaPrep.prepRawMedia is not a function

### ISSUE THREAD

**Issue by DanielG-s** [pedroslopez/whatsapp-web.js#2066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When the code try to send a message i get the error: "Error: Evaluation failed: TypeError: window.Store.MediaPrep.prepRawMedia is not a function"

### Expected behavior

"Client is Ready!" and to send the message 

### Steps to Reproduce the Bug or Issue

i don't know

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

OS: Windows 10
Phone OS: Android
Node.js 18.12.1

**Comment by eowoosh** [comment]
downloadAndDecrypt is not a function

**Comment by DanielG-s** [comment]
[https://github.com/matricce/whatsapp-web.js/commit/076f20a5d9aac21160f4abc57766dfe251841d19](url)

this fix that @matricce did worked to me

**Comment by NissiusRibas** [comment]
Same problem here....

How do I solve?

**Comment by NissiusRibas** [comment]
> [https://github.com/matricce/whatsapp-web.js/commit/076f20a5d9aac21160f4abc57766dfe251841d19](url)
> 
> this fix that @matricce did worked to me

there is no such committee

**Comment by XxQuickSilverZz** [comment]
Evaluation failed: TypeError: window.Store.DownloadManager.downloadAndDecrypt is not a function
 PLEASE HELP!

**Comment by Luskan777** [comment]
same problem here..

**Comment by WesMacedo** [comment]
> User tricce#2828 made these 2 fixes:
> 
> WhatsApp version 2.2312.5
> 
> Fix for Error Downloading Files: [fc58550](https://github.com/pedroslopez/whatsapp-web.js/commit/fc585503d1d011da50aa551b2b9ba61bd6eb4f8e)
> 
> Fix for Error uploading files: Error: Evaluation failed: TypeError: window.Store.MediaPrep.prepRawMedia is not a function [matricce@076f20a](https://github.com/matricce/whatsapp-web.js/commit/076f20a5d9aac21160f4abc57766dfe251841d19)
> 
> ## If anyone wants to try it out, thanks for the feedback, these fixes should work on both 2.2311.5 and 2.2312.5
> @XxQuickSilverZz @DanielG-s

It works perfectly

**Comment by huangpd** [comment]
> [https://github.com/matricce/whatsapp-web.js/commit/076f20a5d9aac21160f4abc57766dfe251841d19](url)
> 
> 这解决了@matricce对我有用

thanks

**Comment by seanesbo** [comment]
> > User tricce#2828 made these 2 fixes:
> > WhatsApp version 2.2312.5
> > Fix for Error Downloading Files: [fc58550](https://github.com/pedroslopez/whatsapp-web.js/commit/fc585503d1d011da50aa551b2b9ba61bd6eb4f8e)
> > Fix for Error uploading files: Error: Evaluation failed: TypeError: window.Store.MediaPrep.prepRawMedia is not a function [matricce@076f20a](https://github.com/matricce/whatsapp-web.js/commit/076f20a5d9aac21160f4abc57766dfe251841d19)
> > ## If anyone wants to try it out, thanks for the feedback, these fixes should work on both 2.2311.5 and 2.2312.5
> > @XxQuickSilverZz @DanielG-s
> 
> It works perfectly

Thanks
