### PR TITLE
fix: Expose onCodeReceivedEvent function

### PR DESCRIPTION
**Pull request by avoylenko**
# PR Details

The `requestPairingCode` method is no longer works and throws `Evaluation failed: TypeError: window.onCodeReceivedEvent is not a function\n    at pptr://__puppeteer_evaluation_script__:20:27` error.

## Description

The `window.onCodeReceivedEvent` is being in injected only if the `pairWithPhoneNumber` option is passed to the Client instance.

## Related Issue(s)

Caused by https://github.com/pedroslopez/whatsapp-web.js/pull/3180

## Motivation and Context

The `requestPairingCode` method should work not only if new option is passed.

## How Has This Been Tested

Locally using my machine.

```
const { Client, LocalAuth } = require('whatsapp-web.js');
const client = new Client(
    {
        puppeteer: {
            args: ['--no-sandbox'],
            headless: false
        },
        authStrategy: new LocalAuth({ dataPath: "." }),
    }
);

client.on('ready', (code) => {
    client.requestPairingCode('38067XXXXXXX', true);
});

client.on('code', (code) => {
    console.log("Linking code:",code);
});

client.initialize();
```

## Types of changes

- [ ] Dependency change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly (index.d.ts).
- [X] I have updated the usage example accordingly (example.js)

### CODE REVIEW

**Comment by alechkos** [comment]
`Client.requestPairingCode` works with `pairWithPhoneNumber` option only.
Try running that code and you'll see what it does to your client state.

```js
// ...

client.on('change_state', (state) => {
    console.log(`[STATE] ${state}${state === WAState.CONNECTED ? '\n' : ''}`);
});

client.on('ready', (code) => {
    await client.requestPairingCode('38067XXXXXXX', true);
});

client.initialize();
```

**Comment by avoylenko** [comment]
@alechkos indeed, I have provided the issue with incorrect code, here are the right one:

```
const { Client, LocalAuth } = require('whatsapp-web.js');

const client = new Client(
    {
        puppeteer: {
            args: ['--no-sandbox'],
            headless: true
        },
        authStrategy: new LocalAuth({ dataPath: "." }),
    }
);

client.on('code', (code) => {
    console.log("Linking code:",code);
});

(async () => {
    await client.initialize();
    await new Promise(r => setTimeout(r, 5000)); // small delay to be sure that instance is ready
    const code = await client.requestPairingCode('38067XXXXXXX', true);
    console.log("Linking code from method:",code);
})();
```

**Comment by alechkos** [comment]
This won't work, your state will change in a circle `OPENING` -> `PAIRING` -> `CONNECTED`.
Also using `await client.initialize();` is not proper. `Client.initialize` is synchronous function that just registers all event listeners defined on `Client`.

**Comment by avoylenko** [comment]
@alechkos thank you for replying. The main issue is that the method `window.onCodeReceivedEvent` is being injected only if the `Client` is started with  `pairWithPhoneNumber` option. This breaks the logic here https://github.com/pedroslopez/whatsapp-web.js/blob/bd677a8a66d44cea8f6d0d4bdb56e41cd0c0ccd5/src/Client.js#L387 which means that you need to know in advance how you will pair the client. Also the recent change adds a breaking change.

**Comment by tofers** [comment]
Never break backward compatibility! 

Those who suffer, I'll throw away my crutch to do as before.

``` 
/* create file untils/Puppeteer.js */

/**
 * Expose a function to the page if it does not exist
 *
 * NOTE:
 * Rewrite it to 'upsertFunction' after updating Puppeteer to 20.6 or higher
 * using page.removeExposedFunction
 * https://pptr.dev/api/puppeteer.page.removeExposedFunction
 *
 * @param {import(puppeteer).Page} page
 * @param {string} name
 * @param {Function} fn
 */
async function exposeFunctionIfAbsent(page, name, fn) {
    const exist = await page.evaluate((name) => {
        return !!window[name];
    }, name);
    if (exist) {
        return;
    }
    await page.exposeFunction(name, fn);
}

module.exports = {exposeFunctionIfAbsent};
```

```
const {exposeFunctionIfAbsent} = require('./untils/Puppeteer');

/* app exress */
app.get('/setAuthenticationPhoneNumber', async (req, res) => {
    let phone = req.query.phone;
    if (phone === undefined) {
        res.status(400).json({error_code: 400, error_text: "required phone"});
        res.end();
    }

 /* emit event  */
        await exposeFunctionIfAbsent(client.pupPage, 'onCodeReceivedEvent', async (code) => {
            /**
             * Emitted when a pairing code is received
             * @event Client#code
             * @param {string} code Code
             * @returns {string} Code that was just received
             */
            client.emit('code', code);
            return code;
        });
        requestPairingCode = await client.requestPairingCode(phone, true);
    

    res.json({code: requestPairingCode});
});
```
