### ISSUE TITLE
requestPairingCode error: Evaluation failed: TypeError: window.onCodeReceivedEvent is not a function

### ISSUE THREAD

**Issue by thadint** [pedroslopez/whatsapp-web.js#21389]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Is this a problem caused by your code, or is it specifically because of the library?

- [x] I have double-checked my code carefully.

### Describe the bug.

Fresh install, not logged in obviously.

```sh
INFO  [2025-08-17T14:17:33.783Z] [index:client]                   Client version:  2.3000.1025996334
224 |         }
225 |         throw error;
226 |     }
227 |     const { exceptionDetails, result: remoteObject } = await callFunctionOnPromise.catch(rewriteError);
228 |     if (exceptionDetails) {
229 |         throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
                    ^
error: Evaluation failed: TypeError: window.onCodeReceivedEvent is not a function
    at pptr://__puppeteer_evaluation_script__:18:23
      at _ExecutionContext_evaluate (V:\User\Documents\Project\Private\wbt\node_modules\.pnpm\puppeteer-core@18.2.1_encoding@0.1.13\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:229:15)

Bun v1.2.20 (Windows x64)
```

### Expected Behavior

Previously worked with version `1.31.1-alpha.0`

### Steps to Reproduce the Bug or Issue

My first attempt is to update my libs (`pnpm up`), but then got this error, so I attempt quick double check lib reversing: 
```sh
pnpm add whatsapp-web.js@latest
bun run .
```

My `requestPairingCode` code clip:
```ts
client.on('qr', async (qr) => {
  console.log('Scan QR:')
  qrcode.generate(qr, { small: true }) // QR print successfully however
  if (PHONE_NUMBER) {
    console.log('Pairing Code:', await client.requestPairingCode(PHONE_NUMBER)) // Error, yep...
  }
})
```

Alpha version:
```sh
pnpm add whatsapp-web.js@next
bun run .
```

Same code, both QR and pairing code printed, no error.

### WhatsApp Account Type

Standard

### Browser Type

Google Chrome

### Operation System Type

Windows

### Phone OS Type

Any

### WhatsApp-Web.js Version

1.32.0

### WhatsApp Web Version

2.3000.1025996334

### Node.js Version

node: "24.3.0", bun: "1.2.20"

### Authentication Strategy

LocalAuth
